# -*- coding: utf-8 -*-
"""Grade_calculator__.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rul1WDvQwBKMGetM_P-w9QPsRVFRLTf0
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit
import streamlit as st

st.set_page_config(page_title="Grade Calculator")

st.title("Grade Calculator")
st.write("Select marks using the slider (No keyboard input required)")

marks = st.slider("Choose Marks", 0, 100, 50)

if marks >= 90:
    grade = "A+"
elif marks >= 75:
    grade = "A"
elif marks >= 60:
    grade = "B"
elif marks >= 40:
    grade = "C"
else:
    grade = "Fail"

st.success(f"Marks: {marks}")
st.info(f"Grade: {grade}")

st.progress(marks)

