# -*- coding: utf-8 -*-
"""petition_form.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/144V5RZlozlklWti-BfEk7Gft3dIn-MZx
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit

import streamlit as st

st.set_page_config(page_title="Online Petition")

st.title("Online Petition")
st.subheader("Petition for the Resignation of Dharmendra Pradhan")

name = st.text_input("Enter Your Name (Uppercase Only)").upper()

signature = st.text_input("Enter Your Signature")

if st.button("Sign Petition"):

    if name == "" or signature == "":
        st.error("Please fill all fields")
    else:
        st.success("Petition Signed Successfully!")

        st.write("### Submitted Details")
        st.write(f"**Name:** {name}")
        st.write(f"**Signature:** {signature}")

