# -*- coding: utf-8 -*-
"""student_list.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/101Mm50n8li2K9pkGj8AKjoSINCw1fiHw
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit

import streamlit as st

st.set_page_config(page_title="Student List App")

st.title("Class Student List App")

st.write("Students can enter their names below.")

if "students" not in st.session_state:
    st.session_state.students = []

student_name = st.text_input("Enter Student Name")

if st.button("Add Name"):

    if student_name.strip() == "":
        st.error("Please enter a valid name")

    elif student_name in st.session_state.students:
        st.warning("Name already exists in the list")

    else:
        st.session_state.students.append(student_name)
        st.success(f"{student_name} added successfully!")

st.subheader("Students List")

if len(st.session_state.students) == 0:
    st.info("No students added yet")
else:
    for i, name in enumerate(st.session_state.students, start=1):
        st.write(f"{i}. {name}")

