# -*- coding: utf-8 -*-
"""Table_generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YJ311rDxZPxGmn3JvfBLZJ3HUcL2GHMi
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit
import streamlit as st

st.set_page_config(page_title="Table Generator")

st.title(" Multiplication Table Generator")

st.write("Select a number using the slider")

number = st.slider("Choose Number", 1, 100, 5)

st.subheader(f"Table of {number}")

for i in range(1, 11):
    st.write(f"{number} × {i} = {number * i}")

